# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.front_door.animation.open.playing
tag @s remove aj.front_door.animation.close.playing