# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:front_door rig_hash set value '6eb1192fd8eff4b20050d7637650a5257b856d24c6b3b1b59dbe5423ce698394'
scoreboard objectives add aj.open.frame dummy
scoreboard objectives add aj.close.frame dummy