# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:front_door rig_hash set value '3d29606ffde414c184cf6c45f76f09e6c833339cee36e61d299f158889f21bf9'
scoreboard objectives add aj.open.frame dummy
scoreboard objectives add aj.close.frame dummy