# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.front_door.animation.open.playing] run function aj:front_door/animations/open/zzz/on_tick
execute if entity @s[tag=aj.front_door.animation.close.playing] run function aj:front_door/animations/close/zzz/on_tick