# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.garage.animation.open.playing] run function aj:garage/animations/open/zzz/on_tick
execute if entity @s[tag=aj.garage.animation.close.playing] run function aj:garage/animations/close/zzz/on_tick