# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:garage rig_hash set value '747802330d836293cb550442535ef8d0f1f87cdf485174e5eec955755356d690'
scoreboard objectives add aj.open.frame dummy
scoreboard objectives add aj.close.frame dummy